### ISSUE TITLE
Weird oscillations in simulator

### ISSUE THREAD

**Issue by micsc12** [collaborative-robotics/surgical_robotics_challenge#37]
I have a issue with the ambf simulator oscillating. I'm trying to control psm2 through the /CRTK/psm2/servo_cp topic. After settling on a point, it starts oscillating like crazy. Here is a video: 

[video](https://youtu.be/j479xtmFzx0)

Any ideas whats going on?

**Comment by micsc12** [comment]
I'm running this on a HP Elitebook 840 G5 laptop. 
Might this simply be a case of the laptop being too slow?

**Comment by adnanmunawar** [comment]
Hmm, it would seem so. You don't really need a powerful PC to run the challenge, a mid tier setup should be fine.

1. Are you running the simulator on Docker/Virtual Machine running Ubuntu on Windows or natively on Ubuntu? 
2. What is the processor model, size of ram and type of GPU on your laptop? 

A common reason for the arms to shake is because of the joint `PID` controllers. If the frequency drops drastically, the `D` gain causes large outputs which destabilizes the joint.

I am attaching the modified [PSM ADF files](https://github.com/collaborative-robotics/surgical_robotics_challenge/files/8430079/PSM_ADFs.zip) with the `D` gain for each joint controller set to `0.`. You can replace the [psm1.yaml](https://github.com/collaborative-robotics/surgical_robotics_challenge/blob/master/ADF/psm1.yaml) and [psm2.yaml](https://github.com/collaborative-robotics/surgical_robotics_challenge/blob/master/ADF/psm1.yaml) files in your copy with these two files to check if the oscillations are gone.

**Comment by micsc12** [comment]
1. I'm running it natively in Ubuntu 20.04. 
2. Intel i7-8650U, 16 GB, Intel HD Graphics. 

The simulator can actually run at 120 Hz (and above) before starting the CRTK interface and my own ros-node. Its only after sending the first servo command that Phx sim rate drops considerably. 
I will now check the modified psm Yaml files and get back to you. Seems like a reasonable fix :)

**Comment by micsc12** [comment]
New PID parameters fixed the problem. And your explanation regarding the control loop frequency dropping makes a lot of sense. Thanks Adnan :)
